# Denavit-Hartenberg parameters for LBR iiwa robot
# Parameters are in SI

DH_params:
    #joint:  [a  alpha  d  theta]
    joint_1: [0 +0.00 0.340 q1]
    joint_2: [0 -pi/2 0.000 q2]
    joint_3: [0 +pi/2 0.400 q3]
    joint_4: [0 +pi/2 0.000 q4]
    joint_5: [0 -pi/2 0.400 q5]
    joint_6: [0 -pi/2 0.000 q6]
    joint_7: [0 +pi/2 0.152 q7]
    tool_length: 0
