# Setting the exact endpoint for a motion
#   position: Cartesian coordinates
#   orientation: roll-pitch-yaw
#   reference_count: how many references to change

set_endpoint:
  first:
    position:
      x: 0.146
      y: 0.09
      z: 1.2
    orientation:
      r: -0.395
      p: -0.4
      y: -0.064
    reference_count: 5
  last:
    position:
      x: 0.0
      y: 0.0
      z: 0.0
    orientation:
      r: 0.0
      p: 0.0
      y: 0.0
    reference_count: 5
    
