# Setting the exact endpoint for a motion
#   position: Cartesian coordinates
#   orientation: quaternion
#   mode: 
#    - position_all: change all joints to reach position
#    - position_last: change only joints 5 and 6 to reach position (they are the most error-prone)
#    - orientation: set exact position and orientation (modify all joint values)
#   reference_count: how many references to change

set_endpoint:
  first:
    position:
      x: 0.0
      y: 0.0
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 0.0
    mode: "position_last"
    reference_count: 5
  last:
    position:
      x: 0.0
      y: 0.0
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 0.0
    mode: "position_last"
    reference_count: 5
    
