controller_names:
  - fake_iiwa14_arm_controller
fake_iiwa14_arm_controller:
    joints:
      - URDFLBRiiwa14Joint1
      - URDFLBRiiwa14Joint2
      - URDFLBRiiwaJoint3
      - URDFLBRiiwaJoint4
      - URDFLBRiiwaJoint5
      - URDFLBRiiwaJoint6
      - URDFLBRiiwaJoint7
initial:
  iiwa14_arm: extended
