fake_joint_driver_node:
  ros__parameters:
    start_position:
      joints:
        - URDFLBRiiwa14Joint1
        - URDFLBRiiwa14Joint2
        - URDFLBRiiwaJoint3
        - URDFLBRiiwaJoint4
        - URDFLBRiiwaJoint5
        - URDFLBRiiwaJoint6
        - URDFLBRiiwaJoint7
      values:
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
